apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendtaapp
  namespace: production
spec:
  selector:
    matchLabels:
      app: backendtaapp
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: backendtaapp
        env: development
    spec:
      containers:
      - name: backendtaapp
        image:  asia.gcr.io/$PROJECT_ID/production/backendtaapp:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"

---
apiVersion: v1
kind: Service
metadata:
  name: backendtaapp
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backendtaapp

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backendtaapp
  namespace: production
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backendtaapp
  targetCPUUtilizationPercentage: 100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendtaapp
  namespace: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kubernetes-ip
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: backendtaapp
spec:
  rules:
    - host: satutitikempat.xyz
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: backendtaapp
              port: 
                number: 8080

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: backendtaapp
  namespace: production
spec:
  domains:
    - satutitikempat.xyz
