apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: Service
metadata:
  name: backendtaapp
  namespace: production
  labels:
    app: backendtaapp
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: backendtaapp
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendtaapp
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendtaapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backendtaapp
    spec:
      containers:
      - name: backendtaapp
        image:  asia.gcr.io/$PROJECT_ID/production/backendtaapp:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: backendtaapp
        resources:
          requests:
            cpu: 50m
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port", "8081",
          "--backend", "127.0.0.1:8080",
          "--service", "SERVICE_NAME",
          "--rollout_strategy", "managed",
        ]
      # [END esp]
        ports:
          - containerPort: 8081
      - name: echo
        image: gcr.io/google-samples/echo-node:1.0
        ports:
          - containerPort: 8080

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backendtaapp
  namespace: production
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backendtaapp
  targetCPUUtilizationPercentage: 100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendtaapp
  namespace: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kubernetes-ip
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: backendtaapp
spec:
  rules:
    - host: satutitikempat.xyz
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: backendtaapp
              port: 
                number: 8081

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: backendtaapp
  namespace: production
spec:
  domains:
    - satutitikempat.xyz
