apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: foo
  name: foo-web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: foo
        tier: backend
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: info
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: redis
        image: gcr.io/my-project/foo-service:3adfa3e
        name: foo-web
        ports:
        - containerPort: 3001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backendtaapp
  namespace: production
  labels:
    app: backendtaapp
spec:
  selector:
    app: backendtaapp
  ports:
  - port: 80
    name: http
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendtaapp
  namespace: production
spec:
  selector:
    matchLabels:
      app: backendtaapp
  strategy:
    type: RollingUpdate
  template: #Template for container
    metadata:
      labels:
        app: backendtaapp
    spec:
      containers:
      - name: backendtaapp
        image:  asia.gcr.io/$PROJECT_ID/production/backendtaapp:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: backendtaapp
        resources:
          requests:
            cpu: 50m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backendtaapp
  namespace: production
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backendtaapp
  targetCPUUtilizationPercentage: 100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendtaapp
  namespace: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kubernetes-ip
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: backendtaapp
spec:
  rules:
    - host: satutitikempat.xyz
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: backendtaapp
              port: 
                number: 80

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: backendtaapp
  namespace: production
spec:
  domains:
    - satutitikempat.xyz
